spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 200 # 생성할 수 있는 thread의 총 개수
      min-spare: 200 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 200 # 수립가능한 connection의 총 개수
    accept-count: 200 # 작업큐의 사이즈
    connection-timeout: 40000 # timeout 판단 기준 시간, 20초


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    redis:
      enabled: false

logging:
  level:
    root: info

