spring:
  config:
    activate:
      on-profile: devel
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.222.11:3306/gather_here?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: gatherhere1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: debug

security:
  salt: 10billion
  jwt:
    secret: 6rmA7IKw7ZWY6rmA7KKF66+86rmA64+E7Jew7J2Y7LKr7ZSE66Gc7KCd7Yq47ISx6rO16riw7JuQ
    access-token:
      minute: 30
      prefix: Bearer
      header:
        name: Authorization
    refresh-token:
      minute: 30
      prefix: Bearer
      header:
        name: Refresh-token

redis:
  host: ec2-3-34-255-150.ap-northeast-2.compute.amazonaws.com
  port: 6379

aws:
    access:
      key: null
    secret:
      key: null
