name: github-actions
on:
  push:
    branches: [ devel ]
jobs:
  server-deploy:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
    - name: checkout-source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    #Gradle 실행권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    #Spring boot application clean and build
    - name: Build with Gradle
      run: ./gradlew clean build

    # docker image 빌드
    - name: Build docker image
      run: docker build -t ${{secrets.DOCKER_ID}}/<gather-here-api> .

    # docker hub 로그인
    - name: Login docker hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_ID}}
        password: ${{secrets.ACCESS_TOKEN}}

    # docker hub 퍼블리시
    - name: Publish to docker hub
      run: docker push ${{secrets.DOCKER_ID}}/<gather-here-api>
