name: github-actions
on:
  push:
    branches: [ devel ]
jobs:
  server-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Create application yml file
        run: |
          New-Item -ItemType Directory -Force -Path .\src\main\resources
          [System.IO.File]::WriteAllText(".\src\main\resources\application-devel.yml", [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.APPLICATION_YML }}")))

      - name: Verify application yml file
        run: type .\src\main\resources\application-devel.yml

      - name: Grant execute permission for gradlew
        run: icacls gradlew /grant:r Everyone:(RX)

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image build and push
        run: |
          docker build -t kimsanha/gatherhere .
          docker push kimsanha/gatherhere

      - name: SANHA_DEV Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SANHA_DEV_SERVER_HOST }}
          username: ${{ secrets.SANHA_DEV_SERVER_USERNAME }}
          password: ${{ secrets.SANHA_DEV_SERVER_PASSWORD }}
          port: ${{ secrets.SANHA_DEV_SERVER_SSH_PORT }}
          timeout: 60s
          script: |
            docker stop gatherhere || true
            docker rm gatherhere || true
            docker pull kimsanha/gatherhere:latest
            docker run -d -p 8080:8080 --name gatherhere kimsanha/gatherhere:latest
