name: github-actions
on:
  push:
    branches: [ devel ]
jobs:
  server-deploy:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Create application yml file
      run: |
        mkdir -p ./src/main/resources
         echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./src/main/resources/application-devel.yml

    - name: Verify application yml file
      run: cat ./src/main/resources/application-devel.yml
#
#    - name: Set yml files
#      uses: microsoft/variable-substitution@v1
#      with:
#        files: ./src/main/resources/application-devel.yml
#      env:
#        aws.access.key: ${{ secrets.AWS_IAM_ACCESS_KEY }}
#        aws.secret.key: ${{ secrets.AWS_IAM_ACCESS_VALUE }}

    #Gradle 실행권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    #Spring boot application clean and build
    - name: Build with Gradle
      run: ./gradlew clean build

    # docker hub 로그인
    - name: Login docker hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_EMAIL}}
        password: ${{secrets.DOCKER_PASSWORD}}

      # docker image build and push
    - name: docker image build and push
      run: |
        docker build -t kimsanha/gatherhere .
        docker push kimsanha/gatherhere

      # GET GitHub IP (5)
    - name: get GitHub IP
      id: ip
      uses: haythem/public-ip@v1.2

    # Configure AWS Credentials (6) - AWS 접근 권한 취득(IAM)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_IAM_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_IAM_ACCESS_VALUE }}
        aws-region: ap-northeast-2

      # Add github ip to AWS (7)
    - name: Add GitHub IP to AWS
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      # AWS EC2 Server Connect & Docker 명령어 실행 (8)
    - name: AWS EC2 Connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_INSTANCE_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_PEM_KEY }}
        port: ${{ secrets.AWS_INSTANCE_PORT }}
        timeout: 60s
        script: |
          sudo docker stop gatherhere
          sudo docker rm gatherhere
          docker pull kimsanha/gatherhere:latest
          docker run -d -p 8080:8080 --name gatherhere kimsanha/gatherhere:latest

      # REMOVE Github IP FROM security group (9)
    - name: Remove IP FROM security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        
