name: github-actions
on:
  push:
    branches: [ devel ]
jobs:
  server-deploy:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
    - name: checkout-source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    #Gradle 실행권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    #Spring boot application clean and build
    - name: Build with Gradle
      run: ./gradlew clean build

    # docker hub 로그인
    - name: Login docker hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_ID}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      # docker image build and push
    - name: docker image build and push
      run: |
        docker build -t kimsanha/gatherhere .
        docker push kimsanha/gatherhere

      # GET GitHub IP (5)
    - name: get GitHub IP
      id: ip
      uses: haythem/public-ip@v1.2

    # Configure AWS Credentials (6) - AWS 접근 권한 취득(IAM)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

      # Add github ip to AWS (7)
    - name: Add GitHub IP to AWS
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      # AWS EC2 Server Connect & Docker 명령어 실행 (8)
    - name: AWS EC2 Connection
      uses: appleboy/ssh-action@v0.1.6
      with:

        host: ${{ secrets.SH_P_HOST }}
        username: ubuntu
        #password: ${{ secrets.SH_P_PASSWORD }}
        key: ${{ secrets.SH_P_KEY }}
        port: ${{ secrets.SH_P_PORT }}
        timeout: 60s
        script: |
          sudo docker stop gatherhere
          sudo docker rm gatherhere
          docker pull kimsanha/gatherhere:latest
          docker run -d -p 8080:8080 --name gatherhere kimsanha/gatherhere:latest

      # REMOVE Github IP FROM security group (9)
    - name: Remove IP FROM security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        
